
//PRODUCT CONSTANTS
export const PRODUCT_LIST_REQUEST='PRODUCT_LIST_REQUEST'
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL'
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS'

export const PRODUCT_DETAILS_REQUEST='PRODUCT_DETAILS_REQUEST'
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL'
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS'

export const PRODUCT_DELETE_REQUEST = 'PRODUCT_DELETE_REQUEST'
export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS'
export const PRODUCT_DELETE_FAIL = 'PRODUCT_DELETE_FAIL'

export const PRODUCT_CREATE_REQUEST = 'PRODUCT_CREATE_REQUEST'
export const PRODUCT_CREATE_SUCCESS = 'PRODUCT_CREATE_SUCCESS'
export const PRODUCT_CREATE_FAIL = 'PRODUCT_CREATE_FAIL'
export const PRODUCT_CREATE_RESET = 'PRODUCT_CREATE_RESET'

export const PRODUCT_UPDATE_REQUEST = 'PRODUCT_UPDATE_REQUEST'
export const PRODUCT_UPDATE_SUCCESS = 'PRODUCT_UPDATE_SUCCESS'
export const PRODUCT_UPDATE_FAIL = 'PRODUCT_UPDATE_FAIL'
export const PRODUCT_UPDATE_RESET = 'PRODUCT_UPDARE_RESET'


export const PRODUCT_CREATE_REVIEW_REQUEST = 'PRODUCT_CREATE_REVIEW_REQUEST'
export const PRODUCT_CREATE_REVIEW_SUCCESS = 'PRODUCT_CREATE_REVIEW_SUCCESS'
export const PRODUCT_CREATE_REVIEW_FAIL = 'PRODUCT_CREATE_REVIEW_FAIL'
export const PRODUCT_CREATE_REVIEW_RESET = 'PRODUCT_CREATE_REVIEW_RESET'

//COLOR CONSTANTS
export const COLOR_LIST_REQUEST='COLOR_LIST_REQUEST'
export const COLOR_LIST_FAIL = 'COLOR_LIST_FAIL'
export const COLOR_LIST_SUCCESS = 'COLOR_LIST_SUCCESS'

export const COLOR_DETAILS_REQUEST='COLOR_DETAILS_REQUEST'
export const COLOR_DETAILS_FAIL = 'COLOR_DETAILS_FAIL'
export const COLOR_DETAILS_SUCCESS = 'COLOR_DETAILS_SUCCESS'

export const COLOR_DELETE_REQUEST = 'COLOR_DELETE_REQUEST'
export const COLOR_DELETE_SUCCESS = 'COLOR_DELETE_SUCCESS'
export const COLOR_DELETE_FAIL = 'COLOR_DELETE_FAIL'

export const COLOR_CREATE_REQUEST = 'COLOR_CREATE_REQUEST'
export const COLOR_CREATE_SUCCESS = 'COLOR_CREATE_SUCCESS'
export const COLOR_CREATE_FAIL = 'COLOR_CREATE_FAIL'
export const COLOR_CREATE_RESET = 'COLOR_CREATE_RESET'

export const COLOR_UPDATE_REQUEST = 'COLOR_UPDATE_REQUEST'
export const COLOR_UPDATE_SUCCESS = 'COLOR_UPDATE_SUCCESS'
export const COLOR_UPDATE_FAIL = 'COLOR_UPDATE_FAIL'
export const COLOR_UPDATE_RESET = 'COLOR_UPDATE_RESET'

//SIZE CONSTANTS
export const SIZE_LIST_REQUEST='SIZE_LIST_REQUEST'
export const SIZE_LIST_FAIL = 'SIZE_LIST_FAIL'
export const SIZE_LIST_SUCCESS = 'SIZE_LIST_SUCCESS'

export const SIZE_DETAILS_REQUEST='SIZE_DETAILS_REQUEST'
export const SIZE_DETAILS_FAIL = 'SIZE_DETAILS_FAIL'
export const SIZE_DETAILS_SUCCESS = 'SIZE_DETAILS_SUCCESS'

export const SIZE_DELETE_REQUEST = 'SIZE_DELETE_REQUEST'
export const SIZE_DELETE_SUCCESS = 'SIZE_DELETE_SUCCESS'
export const SIZE_DELETE_FAIL = 'SIZE_DELETE_FAIL'

export const SIZE_CREATE_REQUEST = 'SIZE_CREATE_REQUEST'
export const SIZE_CREATE_SUCCESS = 'SIZE_CREATE_SUCCESS'
export const SIZE_CREATE_FAIL = 'SIZE_CREATE_FAIL'
export const SIZE_CREATE_RESET = 'SIZE_CREATE_RESET'

export const SIZE_UPDATE_REQUEST = 'SIZE_UPDATE_REQUEST'
export const SIZE_UPDATE_SUCCESS = 'SIZE_UPDATE_SUCCESS'
export const SIZE_UPDATE_FAIL = 'SIZE_UPDATE_FAIL'
export const SIZE_UPDATE_RESET = 'SIZE_UPDATE_RESET'

//CATEGORIES CONSTANTS
export const CATEGORY_LIST_REQUEST='CATEGORY_LIST_REQUEST'
export const CATEGORY_LIST_FAIL = 'CATEGORY_LIST_FAIL'
export const CATEGORY_LIST_SUCCESS = 'CATEGORY_LIST_SUCCESS'

export const CATEGORY_DETAILS_REQUEST='CATEGORY_DETAILS_REQUEST'
export const CATEGORY_DETAILS_FAIL = 'CATEGORY_DETAILS_FAIL'
export const CATEGORY_DETAILS_SUCCESS = 'CATEGORY_DETAILS_SUCCESS'

export const CATEGORY_DELETE_REQUEST = 'CATEGORY_DELETE_REQUEST'
export const CATEGORY_DELETE_SUCCESS = 'CATEGORY_DELETE_SUCCESS'
export const CATEGORY_DELETE_FAIL = 'CATEGORY_DELETE_FAIL'

export const CATEGORY_CREATE_REQUEST = 'CATEGORY_CREATE_REQUEST'
export const CATEGORY_CREATE_SUCCESS = 'CATEGORY_CREATE_SUCCESS'
export const CATEGORY_CREATE_FAIL = 'CATEGORY_CREATE_FAIL'
export const CATEGORY_CREATE_RESET = 'CATEGORY_CREATE_RESET'

export const CATEGORY_UPDATE_REQUEST = 'CATEGORY_UPDATE_REQUEST'
export const CATEGORY_UPDATE_SUCCESS = 'CATEGORY_UPDATE_SUCCESS'
export const CATEGORY_UPDATE_FAIL = 'CATEGORY_UPDATE_FAIL'
export const CATEGORY_UPDATE_RESET = 'CATEGORY_UPDATE_RESET'

//BRANDS CONSTANTS

export const BRAND_LIST_REQUEST='BRAND_LIST_REQUEST'
export const BRAND_LIST_FAIL = 'BRAND_LIST_FAIL'
export const BRAND_LIST_SUCCESS = 'BRAND_LIST_SUCCESS'

export const BRAND_DETAILS_REQUEST='BRAND_DETAILS_REQUEST'
export const BRAND_DETAILS_FAIL = 'BRAND_DETAILS_FAIL'
export const BRAND_DETAILS_SUCCESS = 'BRAND_DETAILS_SUCCESS'

export const BRAND_DELETE_REQUEST = 'BRAND_DELETE_REQUEST'
export const BRAND_DELETE_SUCCESS = 'BRAND_DELETE_SUCCESS'
export const BRAND_DELETE_FAIL = 'BRAND_DELETE_FAIL'

export const BRAND_CREATE_REQUEST = 'BRAND_CREATE_REQUEST'
export const BRAND_CREATE_SUCCESS = 'BRAND_CREATE_SUCCESS'
export const BRAND_CREATE_FAIL = 'BRAND_CREATE_FAIL'
export const BRAND_CREATE_RESET = 'BRAND_CREATE_RESET'

export const BRAND_UPDATE_REQUEST = 'BRAND_UPDATE_REQUEST'
export const BRAND_UPDATE_SUCCESS = 'BRAND_UPDATE_SUCCESS'
export const BRAND_UPDATE_FAIL = 'BRAND_UPDATE_FAIL'
export const BRAND_UPDATE_RESET = 'BRAND_UPDATE_RESET'